apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-embed-nextjs
  description: Example repo of Next.js embedded in Go
  tags:
    - javascript
    - go
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/joeds13/go-embed-nextjs
    github.com/project-slug: joeds13/go-embed-nextjs
spec:
  type: service
  owner: joe@stringer.sh
  lifecycle: experimental
  system: test
